### ISSUE TITLE
Incompatible with latest sqlx/actix-session

### ISSUE THREAD

**Issue by 0xd-0** [chriswk/actix-session-sqlx-postgres#11]
Any plans to update this to latest actix-session(0.10+)/sqlx(0.8+)?

**Comment by chriswk** [comment]
Hi, thanks for creating this issue.

Yes, I'll try to get it done over this weekend.

**Comment by chriswk** [comment]
Done, and published as 0.3.0 :)

**Comment by 0xd-0** [comment]
Thank you for the quick turn around!
